In [1]:
from main import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [2]:
%%time 
#Fitting for Model 1: (without CD) #using curve_fit
fit = Fitting('KMC_NonDynamic_Data_iCovg_iRates.csv','Atomic.csv','Stoich.csv','Param.csv',Input_Type='iCovg_iRates') #covgdep = Allowing for coverage dependance to be considered in the fit
fit.set_rxnconditions() #Sets the Pressures and Temperature as defined from the Param file. (Note: One can also enter them manually - See main.py for syntax)
fit.set_limits_of_integration(fit.Input.iloc[0,0],fit.Input.iloc[-1,0])
fit.n_extract = 0.5

Mass is conserved. 

CPU times: user 20.4 ms, sys: 1.45 ms, total: 21.8 ms
Wall time: 21.7 ms


In [3]:
kfit1 = np.array([7.62920766e+06, 7.84283749e-12, 1.14810513e+09, 3.31188781e+06,
 3.89302597e+04, 1.05772855e-01 ,8.84950863e+00 ,3.71041706e+01])
fit.MKM.k = kfit1
sola1,solta1= MKM1.solve_coverage(plot=True) #Obtains the coverages(sol) with respect to time(solt) and plots them if plot=True (Note: Additional options can be set manually - See main.py for syntax)

In [4]:
fit.MKM.k

array([7.62920766e+06, 7.84283749e-12, 1.14810513e+09, 3.31188781e+06,
       3.89302597e+04, 1.05772855e-01, 8.84950863e+00, 3.71041706e+01])

In [5]:
a = fit.MKM.get_SS_rates_production()[:len(fit.MKM.Pextract())]

In [6]:
print(a)

[-0.04221952 -0.02111715  0.04222021]


In [7]:
actual = np.array([-0.025828993055555468, -0.034275173611110994, 0.033962673611110994])

In [8]:
#Calculating %difference
pd = np.empty(len(a))
for i in np.arange(len(a)):
    pd[i] = np.abs((actual[i]-a[i])/(actual[i]))*100

In [9]:
print(pd)

[63.45786091 38.38936302 24.31355239]
