In [29]:
from main import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

import numpy as np
from scipy.linalg import null_space

In [30]:
import numpy as np
from numpy.linalg import svd

def null(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = svd(A)
    tol = max(atol, rtol * s[0])
    nnz = (s >= tol).sum()
    ns = vh[nnz:].conj().T
    return ns

In [31]:
A = np.array([[-1,0,0,1,0,0,-1],
              [0,-1,0,0,0,1,-1],
              [0,0,0,0,2,-1,-1],
              [0,0,1,-1,-1,0,2]])
A

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2]])

In [32]:
val = np.max(np.abs(null_space(A[:,3:].T)))
np.abs(null_space(A[:,3:].T))/val


array([[1. ],
       [0.5],
       [0.5],
       [1. ]])

In [33]:
np.linalg.matrix_rank(A[:,3:])

3

In [34]:
null(A[:,3:])

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

In [35]:
np.dot(A[:,3:],null_space(A[:,3:]))

array([[ 1.11022302e-16],
       [-4.44089210e-16],
       [ 0.00000000e+00],
       [ 1.11022302e-16]])

In [36]:
#5 steps
A_n = np.array([[-1,0,0,1,0,0,-1],
              [0,-1,0,0,0,1,-1],
              [0,0,0,0,2,-1,-1],
              [0,0,1,-1,-1,0,2],
              [0,0,1,-1,1,-1,1]])
A_n

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2],
       [ 0,  0,  1, -1,  1, -1,  1]])

In [42]:
null_space(A_n[:,3:].T)

array([[-0.5546544 ,  0.51360205],
       [-0.2773272 ,  0.25680103],
       [-0.39227005, -0.4236243 ],
       [-0.66959725, -0.16682327],
       [ 0.11494285,  0.68042532]])

In [47]:
matrix = A_n
rank = np.linalg.matrix_rank(matrix)

# Check if the matrix is linearly independent

if rank == min(matrix.shape):
    print("The matrix is linearly independent.")
else:
    print("The matrix is linearly dependent.")

The matrix is linearly dependent.


In [37]:
val = np.max(np.abs(null_space(A_n[:,3:].T)))
np.abs(null_space(A_n[:,3:].T))/val

array([[0.81515838, 0.75482501],
       [0.40757919, 0.37741251],
       [0.57650713, 0.62258749],
       [0.98408631, 0.24517499],
       [0.16892794, 1.        ]])

In [19]:
np.linalg.matrix_rank(A_n[:,3:])

3

In [9]:
null(A_n[:,3:])

array([[-0.5],
       [-0.5],
       [-0.5],
       [-0.5]])

In [18]:
np.linalg.matrix_rank(A_n[:,3:])

3

In [10]:
np.dot(A_n[:,3:],null_space(A_n[:,3:]))

array([[-1.11022302e-16],
       [-4.44089210e-16],
       [-2.22044605e-16],
       [ 4.44089210e-16],
       [ 1.11022302e-16]])

In [48]:
B = np.array([[-1,0,0,0,1,0,0,0,0,0,-1],
              [0,-1,0,0,0,1,0,0,0,0,-1],
              [0,0,0,0,0,-1,1,1,0,0,-1],
              [0,0,0,0,-1,0,0,-1,1,0,1],
              [0,0,0,0,0,0,1,0,-1,1,-1],
              [0,0,0,1,0,0,-2,0,0,0,2],
              [0,0,1,0,0,0,0,0,0,-1,1]])


In [50]:
val = np.max(np.abs(null_space(B[:,4:].T)))
np.abs(null_space(B[:,4:].T))/val

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [12]:
null_space(B[:,4:])

array([[-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

In [13]:
np.dot(B[:,4:],null_space(B[:,4:]))

array([[ 3.88578059e-16],
       [-1.66533454e-16],
       [-2.22044605e-16],
       [ 0.00000000e+00],
       [-5.55111512e-17],
       [ 0.00000000e+00],
       [ 5.55111512e-17]])