In [1]:
from main import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

import numpy as np
from scipy.linalg import null_space

In [2]:
MKM1 = MKModel('Atomic_1.csv','Stoich_1.csv','Param_1.csv') #Defining the Model

Mass is conserved. 

Thermodynamically constrained (with pseudo Keq)


In [52]:
mat  = MKM1.Stoich.to_numpy()[:,1:]
mat

array([[-1, 0, 0, 1, 0, 0, -1],
       [0, -1, 0, 0, 0, 1, -1],
       [0, 0, 0, 0, 2, -1, -1],
       [0, 0, 1, -1, -1, 0, 2]], dtype=object)

In [4]:
len(MKM1.P)

3

In [5]:
import numpy as np
from numpy.linalg import svd

def null(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = svd(A)
    tol = max(atol, rtol * s[0])
    nnz = (s >= tol).sum()
    ns = vh[nnz:].conj().T
    return ns

In [6]:
A = np.array([[-1,0,0,1,0,0,-1],
              [0,-1,0,0,0,1,-1],
              [0,0,0,0,2,-1,-1],
              [0,0,1,-1,-1,0,2]])
A

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2]])

In [7]:
val = np.max(np.abs(null_space(A[:,3:].T)))
np.abs(null_space(A[:,3:].T))/val
np.linalg.norm(val)

0.6324555320336759

In [8]:
np.linalg.matrix_rank(A[:,3:])

3

In [9]:
null(A[:,3:])

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

In [10]:
np.dot(A[:,3:],null_space(A[:,3:]))

array([[ 1.11022302e-16],
       [-4.44089210e-16],
       [ 0.00000000e+00],
       [ 1.11022302e-16]])

In [11]:
#5 steps
A_n = np.array([[-1,0,0,1,0,0,-1],
              [0,-1,0,0,0,1,-1],
              [0,0,0,0,2,-1,-1],
              [0,0,1,-1,-1,0,2],
              [0,0,1,-1,1,-1,1]])
A_n

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2],
       [ 0,  0,  1, -1,  1, -1,  1]])

In [12]:
null_space(A_n[:,3:].T)

array([[-0.5546544 ,  0.51360205],
       [-0.2773272 ,  0.25680103],
       [-0.39227005, -0.4236243 ],
       [-0.66959725, -0.16682327],
       [ 0.11494285,  0.68042532]])

In [13]:
A

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2]])

In [60]:
A_n

array([[-1,  0,  0,  1,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  1, -1],
       [ 0,  0,  0,  0,  2, -1, -1],
       [ 0,  0,  1, -1, -1,  0,  2],
       [ 0,  0,  1, -1,  1, -1,  1]])

In [65]:
mat = mat.astype(float)

In [66]:
matrix = mat
rank = np.linalg.matrix_rank(matrix)

# Check if the matrix is linearly independent

if rank == min(matrix.shape):
    print("The matrix is linearly independent.")
else:
    print("The matrix is linearly dependent.")

The matrix is linearly independent.


In [50]:

def find_dependent_rows(data_matrix, tolerance=1e-10):
    """
    Finds and returns a list of dependent rows in the given data matrix using SVD.

    Parameters:
        data_matrix (numpy.ndarray): The data matrix as a 2D array.
        tolerance (float, optional): Tolerance value for considering a singular value as zero.
                                     Default is 1e-10.

    Returns:
        list: A list of row indices that are dependent (linearly dependent rows).
    """
    # Perform SVD on the data matrix
    _, singular_values, _ = np.linalg.svd(data_matrix)

    # Set a threshold for identifying zero singular values
    threshold = tolerance * max(data_matrix.shape) * singular_values[0]

    # Find the dependent rows based on singular values
    dependent_rows = [i for i, s in enumerate(singular_values) if abs(s) < threshold]

    return dependent_rows

# Example usage:
data = A_n

dependent_rows = find_dependent_rows(data)
print("Dependent rows:", dependent_rows)

Dependent rows: [4]


In [35]:
import numpy as np
import scipy.linalg as la

# Create a matrix
S = A

# Perform SVD on the matrix
U, S, V = la.svd(S)

# Check if the matrix is independent
if np.allclose(U @ V, np.eye(np.shape(S)[1])):
  print("The matrix is independent")
else:
  print("The matrix is not independent")

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 4)

4

In [148]:
A_n[:,3:]

array([[ 1,  0,  0, -1],
       [ 0,  0,  1, -1],
       [ 0,  2, -1, -1],
       [-1, -1,  0,  2],
       [-1,  1, -1,  1]])

In [28]:
import numpy as np
from scipy.linalg import lstsq

# x = np.linalg.lstsq(A,b)[0]
# Solve for the dependent rows
x, res, rank, s = lstsq(A_n, np.zeros(len(A_n)))

# Print the dependent rows
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [115]:
rank, pivots, rank_eq, info = np.linalg.lstsq(A_n[:,3:], np.ones(A_n[:,3:].shape[0]))
pivots

/var/folders/_p/qwgws2w95qxf051hv3d15ky5_tzjzl/T/ipykernel_73727/3510499109.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  rank, pivots, rank_eq, info = np.linalg.lstsq(A_n[:,3:], np.ones(A_n[:,3:].shape[0]))


array([], dtype=float64)

In [37]:
val = np.max(np.abs(null_space(A_n[:,3:].T)))
np.abs(null_space(A_n[:,3:].T))/val

array([[0.81515838, 0.75482501],
       [0.40757919, 0.37741251],
       [0.57650713, 0.62258749],
       [0.98408631, 0.24517499],
       [0.16892794, 1.        ]])

In [19]:
np.linalg.matrix_rank(A_n[:,3:])

3

In [9]:
null(A_n[:,3:])

array([[-0.5],
       [-0.5],
       [-0.5],
       [-0.5]])

In [18]:
np.linalg.matrix_rank(A_n[:,3:])

3

In [10]:
np.dot(A_n[:,3:],null_space(A_n[:,3:]))

array([[-1.11022302e-16],
       [-4.44089210e-16],
       [-2.22044605e-16],
       [ 4.44089210e-16],
       [ 1.11022302e-16]])

In [48]:
B = np.array([[-1,0,0,0,1,0,0,0,0,0,-1],
              [0,-1,0,0,0,1,0,0,0,0,-1],
              [0,0,0,0,0,-1,1,1,0,0,-1],
              [0,0,0,0,-1,0,0,-1,1,0,1],
              [0,0,0,0,0,0,1,0,-1,1,-1],
              [0,0,0,1,0,0,-2,0,0,0,2],
              [0,0,1,0,0,0,0,0,0,-1,1]])


In [51]:
val = np.max(np.abs(null_space(B[:,4:].T)))
s = np.abs(null_space(B[:,4:].T))/val
np.shape(s)

(7, 1)

In [12]:
null_space(B[:,4:])

array([[-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

In [13]:
np.dot(B[:,4:],null_space(B[:,4:]))

array([[ 3.88578059e-16],
       [-1.66533454e-16],
       [-2.22044605e-16],
       [ 0.00000000e+00],
       [-5.55111512e-17],
       [ 0.00000000e+00],
       [ 5.55111512e-17]])